on:
  schedule:
    - cron: '0 10 * * 1'
  push:
    paths:
      - 'metar_deps/**'
      - '.github/workflows/**metar_deps**'

name: build-metar_deps

jobs:
  build-push:
    runs-on: ubuntu-18.04

    steps:
      - name: Chekout base_dockers
        uses: actions/checkout@v2
        with:
          path: base_dockers

      - name: Chekout metar
        uses: actions/checkout@v2
        with:
          repository: MicrobialGenomics/WMGSPipeline
          token: ${{ secrets.METAR_PASS }}
          path: metar_deps

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Docker image tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: microbialgenomics/metar_deps
          tags: |
            type=schedule,format={{date 'YYYYMMDD'}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base_dockers/metar_deps/Dockerfile
          platforms: linux/386, linux/amd64
          push: true
          no-cache: false
          tags: ${{ steps.meta.outputs.tags }}
